# Generated by Django 5.2 on 2025-04-21 06:15

import django.db.models.deletion
import suggestions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must_item_1', models.CharField(max_length=100)),
                ('must_item_2', models.CharField(max_length=100)),
                ('must_item_3', models.CharField(max_length=100)),
                ('must_item_4', models.CharField(max_length=100)),
                ('must_item_5', models.CharField(max_length=100)),
                ('must_item_6', models.CharField(max_length=100)),
                ('log', models.ForeignKey(default=suggestions.models.get_today_log, on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='logs.log')),
            ],
        ),
    ]
