# Generated by Django 5.2 on 2025-04-26 05:49

import datetime
import django.db.models.deletion
import suggestions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0003_alter_log_extra_items_needed_tomorrow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date(2025, 4, 25))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log', models.ForeignKey(default=suggestions.models.get_today_log, on_delete=django.db.models.deletion.CASCADE, related_name='list_suggestions', to='logs.log')),
            ],
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('is_done', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='suggestions.todolist')),
            ],
        ),
    ]
