# Generated by Django 5.2 on 2025-04-26 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_alter_log_extra_items_needed_tomorrow_and_more'),
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='date',
        ),
        migrations.AlterField(
            model_name='todolist',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_suggestions', to='logs.log'),
        ),
    ]
