# Generated by Django 5.2 on 2025-04-23 05:01

import suggestions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0002_todolist_todoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='date',
            field=models.DateField(default=suggestions.models.yesterday),
        ),
    ]
