# Generated by Django 5.2 on 2025-04-26 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0002_remove_todolist_date_alter_todolist_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
