# Generated by Django 5.2 on 2025-05-01 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0003_todolist_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='title',
        ),
    ]
