# Generated by Django 5.2 on 2025-05-05 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0005_alter_todolist_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='log',
        ),
    ]
