# Generated by Django 5.2 on 2025-04-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_item_today', models.BooleanField()),
                ('schedule_changed_today', models.BooleanField()),
                ('emotion_state_today', models.CharField(choices=[('calm', '落ち着いている'), ('busy', '忙しい'), ('late', '寝坊した')], max_length=10)),
                ('routine_destination_tomorrow', models.BooleanField()),
                ('special_event_tomorrow', models.BooleanField()),
                ('extra_items_needed_tomorrow', models.BooleanField()),
                ('time_difference_tomorrow', models.BooleanField()),
                ('will_forget', models.BooleanField()),
            ],
        ),
    ]
