# Generated by Django 5.2 on 2025-04-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('usage_date', models.DateField()),
                ('usage_time', models.TimeField()),
                ('usage_place', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('daily', '毎日'), ('weekly', '週1'), ('monthly', '月1'), ('once', '今回だけ')], max_length=20)),
                ('last_used_date', models.DateField(blank=True, null=True)),
                ('importance', models.IntegerField(choices=[(1, '1（低）'), (2, '2'), (3, '3'), (4, '4'), (5, '5（高）')])),
                ('recovery_difficulty', models.CharField(choices=[('easy', '買い直せる'), ('medium', '家に戻ればなんとかなる'), ('hard', '代用不可')], max_length=50)),
                ('size', models.CharField(choices=[('small', '小'), ('medium', '中'), ('large', '大')], max_length=10)),
                ('weight', models.CharField(choices=[('light', '軽い'), ('normal', '普通'), ('heavy', '重い')], max_length=10)),
                ('visibility', models.BooleanField(choices=[(True, '目立つ'), (False, '目立ちにくい')], default=True)),
                ('forget_count', models.IntegerField(default=0)),
                ('time_prone', models.CharField(blank=True, choices=[('morning', '朝'), ('noon', '昼'), ('night', '夜')], max_length=10)),
                ('emotion_state', models.CharField(blank=True, choices=[('busy', '慌ただしい'), ('late', '寝坊した'), ('calm', '落ち着いている')], max_length=30)),
                ('reminder_set', models.BooleanField(default=False)),
            ],
        ),
    ]
