# Generated by Django 5.2 on 2025-04-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='will_forget',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
