# Generated by Django 5.2 on 2025-04-17 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='usage_place',
        ),
    ]
