# Generated by Django 5.2 on 2025-04-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_log_will_forget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='extra_items_needed_tomorrow',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='log',
            name='new_item_today',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='log',
            name='routine_destination_tomorrow',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='log',
            name='schedule_changed_today',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='log',
            name='special_event_tomorrow',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='log',
            name='time_difference_tomorrow',
            field=models.BooleanField(default=False),
        ),
    ]
