# Generated by Django 5.2 on 2025-04-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_remove_log_reminder_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='emotion_state',
            field=models.CharField(blank=True, choices=[('busy', '慌ただしい'), ('late', '寝坊した'), ('calm', '落ち着いている')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='forget_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='frequency',
            field=models.CharField(choices=[('daily', '毎日'), ('weekly', '週1'), ('monthly', '月1'), ('once', '今回だけ')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='importance',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='size',
            field=models.CharField(choices=[('small', '小'), ('medium', '中'), ('large', '大')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='time_prone',
            field=models.CharField(blank=True, choices=[('morning', '朝'), ('noon', '昼'), ('night', '夜')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='usage_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='usage_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='weight',
            field=models.CharField(choices=[('light', '軽い'), ('normal', '普通'), ('heavy', '重い')], max_length=10, null=True),
        ),
    ]
