# Generated by Django 5.2 on 2025-04-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_alter_log_emotion_state_alter_log_forget_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='forgotten',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='size',
            field=models.CharField(choices=[('small', '小'), ('medium', '中'), ('large', '大')], max_length=10),
        ),
        migrations.AlterField(
            model_name='log',
            name='weight',
            field=models.CharField(choices=[('light', '軽い'), ('normal', '普通'), ('heavy', '重い')], max_length=10),
        ),
    ]
