# Generated by Django 5.2 on 2025-04-18 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_remove_log_last_used_date_remove_log_usage_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='forgotten',
        ),
    ]
