# Generated by Django 5.2 on 2025-04-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_remove_log_forgotten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='size',
            field=models.CharField(choices=[('small', '小'), ('large', '大')], max_length=10),
        ),
        migrations.AlterField(
            model_name='log',
            name='weight',
            field=models.CharField(choices=[('light', '軽い'), ('heavy', '重い')], max_length=10),
        ),
    ]
